version: '2'
services:
  flask:
    build:
      context: ./flask
      args:
        NGINX_ETC: ./etc-production
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_SETTINGS: 'Docker'
      SECRET_KEY: ${FLASK_SECRET_KEY}
      SOLUTIONS_FOLDER: ${SOLUTIONS_FOLDER}
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /var/log/uwsgi:/var/log/uwsgi
      - ${SSL_LOCATION}:/ssl:ro
      - ${SOLUTIONS_FOLDER}:/var/map-elites/solutions
