version: '2'
services:
  flask:
    build:
      context: ./flask
      args:
        NGINX_ETC: ./etc-http
    ports:
      - "80:80"
    environment:
      APP_SETTINGS: 'Docker'
      SECRET_KEY: ${FLASK_SECRET_KEY}
