#!/bin/sh
cat << EOF >> /docker-entrypoint-initdb.d/init_db.sql

CREATE DATABASE $FLASK_DB_DATABASE;

CREATE USER 'flask'@'172.18.%.%' IDENTIFIED BY '$FLASK_DB_PASSWORD';

GRANT SELECT ON $FLASK_DB_DATABASE.* TO 'flask'@'172.18.%.%';
GRANT INSERT ON $FLASK_DB_DATABASE.* TO 'flask'@'172.18.%.%';
GRANT UPDATE ON $FLASK_DB_DATABASE.* TO 'flask'@'172.18.%.%';
GRANT DELETE ON $FLASK_DB_DATABASE.* TO 'flask'@'172.18.%.%';

FLUSH PRIVILEGES;
EOF
